### ISSUE TITLE
Upgrade to Legolas 0.5

### ISSUE THREAD

**Issue by kleinschmidt** [beacon-biosignals/LegolasFlux.jl#20]
Legolas 0.5 changes how schemas are defined and used.  There's a single schema defined here, `ModelRow`, which needs to be upgraded to use `@schema`/`@version` instead of `@row`.

**Comment by ericphanson** [comment]
This will have to be a breaking change here

**Comment by kleinschmidt** [comment]
Wait, will it?  I'm not 100% sure... as long as we still export the constructor to make a row it may be okay?  At least I thought that this was a "code only" breaking release for legolas, with the serialized arrow being the same...

**Comment by ericphanson** [comment]
Well, if not for anything else, we will probably want a patch version left to be able to backport stuff to a Legolas-v0.4 branch in case a model is stuck on that and desperately needs a bugfix. But also `ModelRow` is kinda a documented thing and it is changing...
